# Generated by Django 4.2.16 on 2024-10-31 14:30

from django.db import migrations

def seed_minerals(apps, schema_editor):
    Mineral = apps.get_model('app', 'Mineral')
    minerals = [
        'Gold',
        'Silver',
        'Copper',
        'Iron',
        'Aluminum',
        'Nickel',
        'Platinum',
        'Palladium',
        'Zinc',
        'Lead',
        'Titanium',
        'Uranium',
        'Cobalt',
        'Lithium',
        'Manganese',
        'Molybdenum',
        'Tungsten',
        'Vanadium',
        'Tin',
        'Diamond',
        'Emerald',
        'Sapphire',
        'Ruby',
        'Amethyst',
        'Topaz',
        'Opal',
        'Aquamarine',
        'Tourmaline',
        'Garnet',
        'Jade',
        'Peridot',
        'Spinel',
        'Tanzanite',
        'Turquoise',
        'Onyx',
        'Zircon',
        'Moonstone',
        'Lapis Lazuli',
    ]
    
    for mineral in minerals:
        Mineral.objects.create(name=mineral)
    
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_minerals),
    ]
