# Generated by Django 4.2.16 on 2024-10-31 14:41

from django.db import migrations

def seed_compagnies(apps, schema_editor):
    Company = apps.get_model('app', 'Company')
    compagnies = [
        'Gem & Giggles Mining Co.',
        'The Treasure Trove Tunneling',
        'Rock Bottom Riches',
        'The Jewel Journey',
        'Dig & Dazzle Delights',
        'Sparkle Spelunkers',
        'The Oreacle',
        'Shiny Sights Exploration',
        'Bling Blasters Inc.',
        'Golden Grotto Ventures',
    ]
    
    for compagny in compagnies:
        Company.objects.create(name=compagny)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241031_1430'),
    ]

    operations = [
        migrations.RunPython(seed_compagnies)
    ]
