# Generated by Django 4.2.16 on 2024-11-05 18:46

from django.db import migrations
from decimal import Decimal

def seed_projects(apps, schema_editor):
    Project = apps.get_model('app', 'Project')
    Company = apps.get_model('app', 'Company')
    Mineral = apps.get_model('app', 'Mineral')
    Document = apps.get_model('app', 'Document')

    minerals_data = ['Gold', 'Silver', 'Copper', 'Iron', 'Aluminum', 'Nickel', 'Platinum', 'Palladium', 'Zinc', 'Lead', 'Titanium', 'Uranium', 'Cobalt', 'Lithium', 'Manganese', 'Molybdenum', 'Tungsten', 'Vanadium', 'Tin', 'Diamond', 'Emerald', 'Sapphire', 'Ruby', 'Amethyst', 'Topaz', 'Opal', 'Aquamarine', 'Tourmaline', 'Garnet', 'Jade', 'Peridot', 'Spinel', 'Tanzanite', 'Turquoise', 'Onyx', 'Zircon', 'Moonstone', 'Lapis Lazuli']
    minerals = [Mineral.objects.get_or_create(name=name)[0] for name in minerals_data]

    companies_data = ["MinerCo", "ExtractLab", "EarthMines", "NexGem", "TerraFind", "GeoSolutions", 'Gem & Giggles Mining Co.', 'The Treasure Trove Tunneling', 'Rock Bottom Riches', 'The Jewel Journey', 'Dig & Dazzle Delights', 'Sparkle Spelunkers', 'The Oreacle', 'Shiny Sights Exploration', 'Bling Blasters Inc.', 'Golden Grotto Ventures']
    companies = [Company.objects.get_or_create(name=name)[0] for name in companies_data]

    documents_data = [1, 2, 3]
    documents = [Document.objects.get_or_create(id=id)[0] for id in documents_data]

    projects_data = [
        {
            "name": f"Projet AlphaMiner",
            "description": f"Description for project AlphaMiner",
            "budget": Decimal("1200000.00"),
            "documents": [],
            "coords": [[45.75, 4.85], [45.751, 4.852], [45.752, 4.853], [45.753, 4.854], [45.752, 4.855], [45.751, 4.854], [45.75, 4.853]],
            "minerals": [minerals[0], minerals[1], minerals[29], minerals[30], minerals[15], minerals[10]],
            "companies": [companies[4]]
        },
        {
            "name": f"Extraction Rubis",
            "description": f"Description for project Extraction Rubis",
            "budget": Decimal("308500.00"),
            "documents": [],
            "coords": [[45.76, 4.84], [45.761, 4.841], [45.762, 4.842], [45.763, 4.843], [45.764, 4.844], [45.763, 4.845], [45.762, 4.846], [45.761, 4.845], [45.76, 4.844], [45.759, 4.843]],
            "minerals": [minerals[0], minerals[2], minerals[30], minerals[25], minerals[35]],
            "companies": [companies[3], companies[13]]
        },
        {
            "name": f"Mine de Cristal",
            "description": f"Description for project Mine de Cristal",
            "budget": Decimal("500000.00"),
            "documents": [],
            "coords": [[45.74, 4.86], [45.741, 4.861], [45.742, 4.862], [45.741, 4.863], [45.74, 4.862], [45.739, 4.861]],
            "minerals": [minerals[1], minerals[4], minerals[5], minerals[29], minerals[30], minerals[30], minerals[12], minerals[21]],
            "companies": [companies[0], companies[1], companies[10]]
        },
        {
            "name": f"Opération GoldLine",
            "description": f"Description for project Opération GoldLine",
            "budget": Decimal("750000.00"),
            "documents": [],
            "coords": [[45.75, 4.84], [45.751, 4.841], [45.752, 4.842], [45.753, 4.843], [45.752, 4.844], [45.751, 4.843], [45.75, 4.842], [45.749, 4.841]],
            "minerals": [minerals[8], minerals[14], minerals[33], minerals[22]],
            "companies": [companies[12]]
        },
        {
            "name": f"Silver Surge",
            "description": f"Description for project Silver Surge",
            "budget": Decimal("100000.00"),
            "documents": [],
            "coords": [[45.77, 4.85], [45.771, 4.851], [45.772, 4.852], [45.773, 4.853], [45.774, 4.854], [45.773, 4.855], [45.772, 4.856], [45.771, 4.855], [45.77, 4.854], [45.769, 4.853], [45.768, 4.852], [45.767, 4.851]],
            "minerals": [minerals[20], minerals[16], minerals[3], minerals[6]],
            "companies": [companies[9], companies[8]]
        },
        {
            "name": f"Projet Minerai Noir",
            "description": f"Description for project Projet Minerai Noir",
            "budget": Decimal("200000.00"),
            "documents": [],
            "coords": [[45.74, 4.84], [45.741, 4.841], [45.742, 4.842], [45.743, 4.843], [45.742, 4.844], [45.741, 4.845], [45.74, 4.844], [45.739, 4.843], [45.738, 4.842]],
            "minerals": [minerals[11], minerals[26]],
            "companies": [companies[5]]
        },
        {
            "name": f"Exploration Zéphyr",
            "description": f"Description for project Exploration Zéphyr",
            "budget": Decimal("455000.00"),
            "documents": [],
            "coords": [[45.78, 4.84], [45.781, 4.841], [45.782, 4.842], [45.781, 4.843], [45.78, 4.842]],
            "minerals": [minerals[10], minerals[9], minerals[24], minerals[25], minerals[4], minerals[17]],
            "companies": [companies[3], companies[6], companies[4]]
        },
        {
            "name": f"Terra Minéral",
            "description": f"Description for project Terra Minéral",
            "budget": Decimal("1500000.00"),
            "documents": [documents[1]],
            "coords": [[45.75, 4.88], [45.751, 4.881], [45.752, 4.882], [45.753, 4.883], [45.754, 4.884], [45.753, 4.885], [45.752, 4.886], [45.751, 4.885], [45.75, 4.884], [45.749, 4.883], [45.748, 4.882], [45.747, 4.881], [45.746, 4.88], [45.747, 4.879], [45.748, 4.878]],
            "minerals": [minerals[11], minerals[1], minerals[3], minerals[25], minerals[34], minerals[33], minerals[24], minerals[28]],
            "companies": [companies[0], companies[1], companies[2], companies[14], companies[13]]
        },
        {
            "name": f"Blue Diamond",
            "description": f"Description for project Blue Diamond",
            "budget": Decimal("3000000.00"),
            "documents": [],
            "coords": [[45.76, 4.87], [45.761, 4.871], [45.762, 4.872], [45.763, 4.873], [45.762, 4.874], [45.761, 4.873], [45.76, 4.872], [45.759, 4.871]],
            "minerals": [minerals[13], minerals[9], minerals[19]],
            "companies": [companies[11], companies[5]]
        },
        {
            "name": f"Nexus Miner",
            "description": f"Description for project Nexus Miner",
            "budget": Decimal("1000000.00"),
            "documents": [],
            "coords": [[45.73, 4.85], [45.731, 4.851], [45.732, 4.852], [45.733, 4.853], [45.732, 4.854], [45.731, 4.855], [45.73, 4.854], [45.729, 4.853], [45.728, 4.852], [45.727, 4.851], [45.726, 4.85]],
            "minerals": [minerals[10]],
            "companies": [companies[7]]
        },
        {
            "name": f"Lucky Miner",
            "description": f"Description for project Lucky Miner",
            "budget": Decimal("10000500.00"),
            "documents": [documents[2]],
            "coords": [[45.78853,4.833555],[45.79044,4.836473],[45.79146,4.842309],[45.792005,4.84797471],[45.7934412,4.85321041],[45.79541604,4.856042875],[45.7967337,4.85801698],[45.7989476,4.85990523],[45.8003236,4.86187934],[45.80110116,4.86462594],[45.8009817,4.86625678],[45.8016403,4.8669433],[45.8042134,4.86728667],[45.8063679,4.86720081],[45.8075033,4.86634255],[45.80840195,4.865055065],[45.80822196,4.86299518],[45.8067852,4.86136434],[45.80588896,4.85990523],[45.80493116,4.8597335],[45.80403314,4.85939023],[45.8035546,4.85750199],[45.8042134,4.85707286],[45.8051701,4.856815365],[45.80600804,4.85707286],[45.8067852,4.85527038],[45.80720474,4.85372549],[45.8081025,4.85312464],[45.80911946,4.85389703],[45.8096578,4.85218042],[45.80971725,4.85072131],[45.8091795,4.84883306],[45.8084614,4.84797471],[45.8072647,4.847202315],[45.8063679,4.846429825],[45.80588896,4.84514234],[45.8046914,4.843683225],[45.8034358,4.84316823],[45.8016403,4.84205248],[45.8003236,4.84179497],[45.799366,4.84059336],[45.7981695,4.83930588],[45.79751165,4.838190025],[45.79703225,4.83716014],[45.7963148,4.83552939],[45.7963148,4.83467103],[45.7960153,4.83355528],[45.7958356,4.832696925],[45.79511765,4.83089445],[45.7934412,4.83063695],[45.7923648,4.83080868],[45.7911071,4.83089445],[45.7891927,4.83115193],[45.7888933,4.83020782],[45.7880553,4.83003619],[45.7873372,4.83055118],[45.7869188,4.832096065]],
            "minerals": [minerals[6], minerals[18], minerals[20], minerals[26]],
            "companies": [companies[3], companies[5]]
        }
    ]

    for project_data in projects_data:
        project = Project.objects.create(
            name=project_data["name"],
            description=project_data["description"],
            budget=project_data["budget"],
            coords=project_data["coords"],
        )
        project.minerals.set(project_data["minerals"])
        project.companies.set(project_data["companies"])
        project.documents.set(project_data["documents"])

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20241105_1846'),
    ]

    operations = [
        migrations.RunPython(seed_projects),
    ]
